language: node_js
sudo: required
cache: false
os:
  - linux
node_js:
  - "11.10.0"

services:
  - xvfb

addons:
  chrome: stable
  firefox: stable

script:
- npm install
- npm run lint
- npm run build
- npm run test:node
- npm run test:browser
